export const way = [
    "At the moment, I can assist you with navigating through NeST. For example, say ",
    "Currently, I can help you find your way around NeST. For instance, say ",
    "Right now, I'm here to guide you through NeST. For example, say ",
    "Presently, I can aid you in navigating NeST. For instance, say ",
    "For now, I can help you explore NeST. For example, say ",
    "At this time, I can guide you through NeST. For instance, say ",
    "Currently, I'm here to assist you with NeST navigation. For example, say ",
    "Right now, I can help you with finding your way around NeST. For instance, say ",
    "Presently, I can assist you in exploring NeST. For example, say ",
    "For now, I can help you with NeST navigation. For instance, say ",
    "At the moment, I can guide you through the features of NeST. For example, say ",
    "Currently, I can assist you with exploring NeST. For instance, say ",
    "Right now, I'm here to help you navigate NeST. For example, say ",
    "Presently, I can help you find your way through NeST. For instance, say ",
    "For now, I can assist you with understanding NeST. For example, say ",
    "At this time, I can help you navigate the features of NeST. For instance, say ",
    "Currently, I'm here to guide you through NeST. For example, say ",
    "Right now, I can aid you in exploring NeST. For instance, say ",
    "Presently, I can help you with navigating NeST. For example, say ",
    "For now, I can guide you through NeST. For instance, say ",
    "At the moment, I can assist you with finding your way in NeST. For example, say ",
    "Currently, I can help you discover NeST’s features. For instance, say ",
    "Right now, I’m here to support you with NeST navigation. For example, say ",
    "Presently, I can assist you in exploring different aspects of NeST. For instance, say ",
    "For now, I can guide you through the various sections of NeST. For example, say ",
    "At this time, I can help you understand how to navigate NeST. For example, say ",
    "Currently, I’m here to assist you in exploring NeST’s functionalities. For example, say ",
    "Right now, I can help you find your way around NeST’s features. For example, say ",
    "Presently, I can guide you through NeST’s options. For example, say ",
    "For now, I can support you in navigating NeST’s interface. For example, say ",
    "At the moment, I can help you understand NeST’s navigation. For example, say ",
    "Currently, I can guide you through the various features of NeST. For example, say ",
    "Right now, I’m here to assist you with NeST’s functions. For example, say ",
    "Presently, I can help you find your way in NeST. For example, say ",
    "For now, I can support you in exploring NeST’s capabilities. For example, say ",
    "At this time, I can assist you with understanding NeST’s features. For example, say ",
    "Currently, I can help you with navigating through NeST’s sections. For example, say ",
    "Right now, I’m here to guide you through NeST’s interface. For example, say ",
    "Presently, I can assist you in discovering NeST’s options. For example, say ",
    "For now, I can help you explore the features of NeST. For example, say ",
    "At the moment, I can guide you through the different parts of NeST. For example, say ",
    "Currently, I can assist you with understanding NeST’s layout. For example, say ",
    "Right now, I’m here to help you explore the functionalities of NeST. For example, say ",
    "Presently, I can support you with finding your way in NeST. For example, say ",
    "For now, I can guide you through NeST’s various features. For example, say ",
    "At this time, I can assist you with NeST’s navigation tools. For example, say ",
    "Currently, I can help you find your way through NeST’s interface. For example, say ",
    "Right now, I’m here to assist you with exploring NeST. For example, say ",
    "Presently, I can guide you through the navigation options in NeST. For example, say ",
    "For now, I can help you understand how to use NeST. For example, say ",
    "At the moment, I can support you with NeST’s features. For example, say ",
    "Currently, I can guide you through NeST’s functions. For example, say ",
    "Right now, I can help you navigate the various features of NeST. For example, say ",
    "Presently, I can assist you with exploring NeST’s functionalities. For example, say ",
    "For now, I can help you discover how to navigate NeST. For example, say ",
    "At this time, I can guide you through NeST’s main features. For example, say ",
    "Currently, I can assist you in exploring the options available in NeST. For example, say ",
    "Right now, I’m here to support you with NeST’s capabilities. For example, say ",
    "Presently, I can help you navigate NeST’s tools and features. For example, say ",
    "For now, I can assist you with discovering NeST’s options. For example, say ",
    "At the moment, I can guide you through NeST’s different sections. For example, say ",
    "Currently, I can help you find your way around NeST’s features. For example, say ",
    "Right now, I’m here to assist you with NeST’s navigation options. For example, say ",
    "Presently, I can support you in exploring NeST’s capabilities. For example, say ",
    "For now, I can guide you through the features and tools of NeST. For example, say ",
    "At this time, I can help you with NeST’s various functions. For example, say ",
    "Currently, I can assist you with navigating through NeST’s features. For example, say ",
    "Right now, I’m here to help you discover NeST’s functionalities. For example, say ",
    "Presently, I can guide you through the different features of NeST. For example, say ",
    "For now, I can assist you in exploring the capabilities of NeST. For example, say ",
    "At the moment, I can help you navigate NeST’s different features. For example, say ",
    "Currently, I can guide you through the various sections of NeST. For example, say ",
    "Right now, I can assist you with exploring NeST’s functions. For example, say ",
    "Presently, I can help you understand how to use NeST. For example, say ",
    "For now, I can guide you through the main features of NeST. For example, say ",
    "At this time, I’m here to help you explore NeST’s options. For example, say ",
    "Currently, I can assist you with finding your way in NeST. For example, say ",
    "Right now, I can help you navigate NeST’s main features. For example, say ",
    "Presently, I can support you with discovering NeST’s functionalities. For example, say ",
    "For now, I can guide you through the various features and options in NeST. For example, say ",
    "At the moment, I can help you with exploring NeST’s sections. For example, say ",
    "Currently, I’m here to assist you with NeST’s navigation. For example, say ",
    "Right now, I can help you find your way around NeST’s features. For example, say ",
    "Presently, I can guide you through the tools available in NeST. For example, say ",
    "For now, I can assist you in exploring NeST’s main features. For example, say ",
    "At this time, I can help you navigate through the options in NeST. For example, say ",
    "Currently, I’m here to guide you through NeST’s capabilities. For example, say ",
    "Right now, I can help you understand NeST’s various features. For example, say ",
    "Presently, I can support you with exploring the features of NeST. For example, say ",
    "For now, I can guide you through the main aspects of NeST. For example, say ",
    "At the moment, I can assist you with discovering NeST’s options. For example, say ",
    "Currently, I can help you explore the different features of NeST. For example, say ",
    "Right now, I can guide you through NeST’s tools. For example, say ",
    "Presently, I’m here to assist you with understanding NeST’s features. For example, say ",
    "For now, I can help you navigate the various options in NeST. For example, say ",
    "At this time, I can guide you through NeST’s navigation options. For example, say ",
    "Currently, I can assist you with finding your way through NeST’s tools. For example, say ",
    "Right now, I can help you explore NeST’s features and capabilities. For example, say ",
    "Presently, I can guide you through the different aspects of NeST. For example, say ",
    "For now, I can support you with NeST’s main features. For example, say ",
    "At the moment, I’m here to assist you with navigating NeST’s functionalities. For example, say "
];


export const greeting = [
    "Hi there! I'm NeST Bot, how may I help you today?",
    "Greetings! NeST Bot here. What can I do for you today?",
    "Hello! NeST Bot at your service. How can I assist you?",
    "Hi! I'm NeST Bot. What assistance do you need today?",
    "Hey! NeST Bot ready to help. How can I assist you today?",
    "Hello! I'm NeST Bot. How can I be of service today?",
    "Hi! NeST Bot here. How can I help you today?",
    "Greetings! I'm NeST Bot. What do you need help with today?",
    "Hello! NeST Bot here. How can I support you today?",
    "Hi there! I'm NeST Bot. How can I assist you today?",
    "Hey! NeST Bot at your service. How may I help you today?",
    "Hello! NeST Bot ready to assist. What can I do for you today?",
    "Hi! I'm NeST Bot. How can I help you today?",
    "Greetings! NeST Bot here. How may I assist you today?",
    "Hello! I'm NeST Bot. How can I be of help today?",
    "Hi there! NeST Bot ready to serve. What do you need today?",
    "Hey! NeST Bot here. How can I support you today?",
    "Hello! I'm NeST Bot. What assistance do you require today?",
    "Hi! NeST Bot at your service. How can I assist you today?",
    "Greetings! NeST Bot here. What can I help you with today?",
    "Hello! I'm NeST Bot. How can I assist you today?",
    "Hi! NeST Bot ready to help. What do you need?",
    "Greetings! I'm NeST Bot, here to assist you today.",
    "Hello! NeST Bot at your service. Need help?",
    "Hi there! I'm NeST Bot. What can I do for you?",
    "Hey! NeST Bot here. How can I support you?",
    "Greetings! I'm NeST Bot. How may I assist you today?",
    "Hello! I'm NeST Bot, ready to help. What can I do?",
    "Hi! NeST Bot here. How can I be of service today?",
    "Greetings! NeST Bot here. How can I help you?",
    "Hello! I'm NeST Bot. What assistance do you need today?",
    "Hi there! NeST Bot here. How may I help you today?",
    "Hey! NeST Bot at your service. Need assistance?",
    "Greetings! I'm NeST Bot. How can I assist you?",
    "Hello! NeST Bot here. How can I support you?",
    "Hi! I'm NeST Bot, ready to help you today.",
    "Greetings! NeST Bot at your service. How may I assist?",
    "Hello! I'm NeST Bot. How can I help you?",
    "Hi there! NeST Bot ready to assist. What do you need?",
    "Hey! NeST Bot here. How may I help you?",
    "Greetings! NeST Bot here to assist. What can I do for you?",
    "Hello! I'm NeST Bot. How can I be of service?",
    "Hi! NeST Bot here. How can I support you today?",
    "Greetings! NeST Bot ready to help. What can I do?",
    "Hello! I'm NeST Bot. How can I assist you today?",
    "Hi there! NeST Bot here. Need help?",
    "Hey! NeST Bot at your service. How can I help?",
    "Greetings! I'm NeST Bot. What can I do for you?",
    "Hello! NeST Bot here. How may I assist?",
    "Hi! I'm NeST Bot. How can I help you today?",
    "Greetings! NeST Bot at your service. Need assistance?",
    "Hello! I'm NeST Bot. What do you need today?",
    "Hi there! NeST Bot here. How can I assist?",
    "Hey! NeST Bot ready to help. What do you need?",
    "Greetings! NeST Bot here. How can I support you today?",
    "Hello! I'm NeST Bot. How can I be of service today?",
    "Hi! NeST Bot here. How can I assist you?",
    "Greetings! NeST Bot at your service. How may I help you?",
    "Hello! I'm NeST Bot. How can I support you?",
    "Hi there! NeST Bot here. What can I do for you today?",
    "Hey! NeST Bot ready to assist. How can I help you?",
    "Greetings! I'm NeST Bot. How can I assist you today?",
    "Hello! NeST Bot here. What assistance do you need?",
    "Hi! I'm NeST Bot, ready to help you today.",
    "Greetings! NeST Bot at your service. How can I help?",
    "Hello! I'm NeST Bot. How can I be of assistance?",
    "Hi there! NeST Bot here. How can I help you today?",
    "Hey! NeST Bot here. What can I do for you?",
    "Greetings! I'm NeST Bot. Need help?",
    "Hello! NeST Bot ready to assist. How can I support you?",
    "Hi! NeST Bot here. How can I help today?",
    "Greetings! NeST Bot at your service. What do you need?",
    "Hello! I'm NeST Bot. How can I support you today?",
    "Hi there! NeST Bot ready to help. How may I assist you?",
    "Hey! NeST Bot here. What do you need today?",
    "Greetings! I'm NeST Bot. How can I help?",
    "Hello! NeST Bot at your service. How may I support you?",
    "Hi! I'm NeST Bot. How can I assist you today?",
    "Greetings! NeST Bot here. What can I do for you?",
    "Hello! I'm NeST Bot, ready to help you today.",
    "Hi there! NeST Bot here. Need assistance?",
    "Hey! NeST Bot ready to assist. How can I help?",
    "Greetings! NeST Bot here. How may I assist you?",
    "Hello! NeST Bot at your service. What do you need?",
    "Hi! I'm NeST Bot. How can I help you today?",
    "Greetings! NeST Bot here to help. What do you need?"
];


export const commands = [
    'stop',
    'initiation',
    'ppra dashboard',
    'procuring entity dashboard',
    'procuring entity auditing',
    'tenderer management',
    'framework agreement',
    'calloff',
    'app management',
    'pre qualification',
    'opening',
    'micro value',
    'tender evaluation',
    'post qualification',
    'negotiation',
    'tender award',
    'tender lookup',
    'complaint management',
    'government supplier',
    'tender board',
    'contracts',
    'pe management',
    'bills',
    'templates management',
    'pe self registration',
    'landing'
];
