export enum TemplateDocumentTypesEnum {
  TENDER_DOCUMENT = 'TENDER_DOCUMENT',
  TENDER_CONTRACT = 'TENDER_CONTRACT',
  AGREEMENT_DOCUMENT = 'AGREEMENT_DOCUMENT',
  PRE_QUALIFICATION_DOCUMENT = 'PRE_QUALIFICATION_DOCUMENT',
}
